EDA  And Feature Engineering Flight Price Prediction

In [ ]:
#  Features
# The values  features of the cleaned dataset arre explained below:

# 1. Ariline: The name of the airline company is stored in the airline column. It is a categorical feature having 6 different airlines. 
# 2. Date_Of_Journey
# 3. Flight: Flight stores information regarding the plane's flight code. It is categorical feature.
# 4. Source City: City from which the flight takes off. It is a categorical feature having 6 unique cities.
# 5. Destination;
# 6. Route
# 7. Departure Time: This is derived categorical feature obtained created by grouping time periods into bins. it stores information about the 
# departure time and have 6 unique time tables.
# 8. Arrival Time: This is derived categorical feature created by grouping time intevals into bins. It has 6  distinct time tabels and keep
# information about the arrival time
# 9.Total_Stops: Acategorical feature with 3 distinct values that stores the number of stops between the source and destinations cities.
# 10. Class: A categorical feature that contains information on seat class; It has two distinct values: Business and Economy.
# 11: Duration: A continouous feature that displays that overall amount of time it takes to travel betwewen cities in hours.
# 12. Days Left: This is a derived characterstic that is calculated by substracting the trip date by the booking date.
# 13. Price : Target variable store information of the ticket price.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('fligh_price.csv')
df

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Akasa Air,2025-03-17,QP5463,Bangalore,Chennai,Bangalore -> Chennai,2025-03-17 21:50:00,2025-03-18 01:46:00,1 Stop,Economy,3h 56m,2,4949
996,Go First,2025-05-07,G82932,Mumbai,Delhi,Mumbai -> Delhi,2025-05-07 13:00:00,2025-05-07 14:08:00,Non-stop,Economy,1h 8m,17,6779
997,Air India,2025-02-20,AI7608,Delhi,Mumbai,Delhi -> Mumbai,2025-02-20 06:10:00,2025-02-20 18:09:00,2+ Stops,Business,11h 59m,6,14052
998,Air India,2025-05-11,AI581,Chennai,Bangalore,Chennai -> Bangalore,2025-05-11 00:20:00,2025-05-11 09:47:00,2+ Stops,Business,9h 27m,35,22911
999,SpiceJet,2025-05-16,SG6355,Chennai,Delhi,Chennai -> Delhi,2025-05-16 20:10:00,2025-05-17 00:36:00,Non-stop,Economy,4h 26m,57,7693

In [4]:
df.head()

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          1000 non-null   object
 1   Date_Of_Journey  1000 non-null   object
 2   Flight           1000 non-null   object
 3   Source_City      1000 non-null   object
 4   Destination      1000 non-null   object
 5   Route            1000 non-null   object
 6   Departure_Time   1000 non-null   object
 7   Arrivala_Time    1000 non-null   object
 8   Total_Stops      1000 non-null   object
 9   Class            1000 non-null   object
 10  Duration         1000 non-null   object
 11  Days_Left        1000 non-null   int64
 12  Price            1000 non-null   int64
dtypes: int64(2), object(11)
memory usage: 101.7+ KB

In [5]:
df.describe()

         Days_Left         Price
count  1000.000000   1000.000000
mean     30.175000  13183.623000
std      17.164761   7540.390451
min       1.000000   2527.000000
25%      15.000000   7740.500000
50%      31.000000  10774.000000
75%      45.000000  17376.500000
max      60.000000  37719.000000

In [7]:
df.head()

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859

In [6]:
df.head(2)

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718

In [9]:
df['Date_Of_Journey'].str.split('-')

0      [2025, 04, 22]
1      [2025, 03, 12]
2      [2025, 05, 25]
3      [2025, 02, 17]
4      [2025, 05, 25]
            ...
995    [2025, 03, 17]
996    [2025, 05, 07]
997    [2025, 02, 20]
998    [2025, 05, 11]
999    [2025, 05, 16]
Name: Date_Of_Journey, Length: 1000, dtype: object

In [7]:
df['Date_Of_Journey'].str.split('-').str[2]

0      22
1      12
2      25
3      17
4      25
       ..
995    17
996    07
997    20
998    11
999    16
Name: Date_Of_Journey, Length: 1000, dtype: object

In [8]:
df['Date']= df['Date_Of_Journey'].str.split('-').str[2]

In [42]:
df.head()

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,date
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032,25
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971,17
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859,25

In [9]:
df['Month']= df['Date_Of_Journey'].str.split('-').str[1]

In [10]:
df['Year']= df['Date_Of_Journey'].str.split('-').str[0]

In [11]:
df.head()

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,04,2025
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,03,2025
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032,25,05,2025
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971,17,02,2025
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859,25,05,2025