EDA  And Feature Engineering Flight Price Prediction

In [ ]:
#  Features
# The values  features of the cleaned dataset arre explained below:

# 1. Ariline: The name of the airline company is stored in the airline column. It is a categorical feature having 6 different airlines. 
# 2. Date_Of_Journey
# 3. Flight: Flight stores information regarding the plane's flight code. It is categorical feature.
# 4. Source City: City from which the flight takes off. It is a categorical feature having 6 unique cities.
# 5. Destination;
# 6. Route
# 7. Departure Time: This is derived categorical feature obtained created by grouping time periods into bins. it stores information about the 
# departure time and have 6 unique time tables.
# 8. Arrival Time: This is derived categorical feature created by grouping time intevals into bins. It has 6  distinct time tabels and keep
# information about the arrival time
# 9.Total_Stops: Acategorical feature with 3 distinct values that stores the number of stops between the source and destinations cities.
# 10. Class: A categorical feature that contains information on seat class; It has two distinct values: Business and Economy.
# 11: Duration: A continouous feature that displays that overall amount of time it takes to travel betwewen cities in hours.
# 12. Days Left: This is a derived characterstic that is calculated by substracting the trip date by the booking date.
# 13. Price : Target variable store information of the ticket price.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('fligh_price.csv')
df

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Akasa Air,2025-03-17,QP5463,Bangalore,Chennai,Bangalore -> Chennai,2025-03-17 21:50:00,2025-03-18 01:46:00,1 Stop,Economy,3h 56m,2,4949
996,Go First,2025-05-07,G82932,Mumbai,Delhi,Mumbai -> Delhi,2025-05-07 13:00:00,2025-05-07 14:08:00,Non-stop,Economy,1h 8m,17,6779
997,Air India,2025-02-20,AI7608,Delhi,Mumbai,Delhi -> Mumbai,2025-02-20 06:10:00,2025-02-20 18:09:00,2+ Stops,Business,11h 59m,6,14052
998,Air India,2025-05-11,AI581,Chennai,Bangalore,Chennai -> Bangalore,2025-05-11 00:20:00,2025-05-11 09:47:00,2+ Stops,Business,9h 27m,35,22911
999,SpiceJet,2025-05-16,SG6355,Chennai,Delhi,Chennai -> Delhi,2025-05-16 20:10:00,2025-05-17 00:36:00,Non-stop,Economy,4h 26m,57,7693

In [3]:
df.head()

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          1000 non-null   object
 1   Date_Of_Journey  1000 non-null   object
 2   Flight           1000 non-null   object
 3   Source_City      1000 non-null   object
 4   Destination      1000 non-null   object
 5   Route            1000 non-null   object
 6   Departure_Time   1000 non-null   object
 7   Arrivala_Time    1000 non-null   object
 8   Total_Stops      1000 non-null   object
 9   Class            1000 non-null   object
 10  Duration         1000 non-null   object
 11  Days_Left        1000 non-null   int64
 12  Price            1000 non-null   int64
dtypes: int64(2), object(11)
memory usage: 101.7+ KB

In [4]:
df.describe()

         Days_Left         Price
count  1000.000000   1000.000000
mean     30.175000  13183.623000
std      17.164761   7540.390451
min       1.000000   2527.000000
25%      15.000000   7740.500000
50%      31.000000  10774.000000
75%      45.000000  17376.500000
max      60.000000  37719.000000

In [5]:
df.head()

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859

In [6]:
df.head(2)

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718

In [7]:
df['Date_Of_Journey'].str.split('-')

0      [2025, 04, 22]
1      [2025, 03, 12]
2      [2025, 05, 25]
3      [2025, 02, 17]
4      [2025, 05, 25]
            ...
995    [2025, 03, 17]
996    [2025, 05, 07]
997    [2025, 02, 20]
998    [2025, 05, 11]
999    [2025, 05, 16]
Name: Date_Of_Journey, Length: 1000, dtype: object

In [8]:
df['Date_Of_Journey'].str.split('-').str[2]

0      22
1      12
2      25
3      17
4      25
       ..
995    17
996    07
997    20
998    11
999    16
Name: Date_Of_Journey, Length: 1000, dtype: object

In [9]:
df['Date']= df['Date_Of_Journey'].str.split('-').str[2]

In [10]:
df.head()

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032,25
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971,17
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859,25

In [11]:
df['Month']= df['Date_Of_Journey'].str.split('-').str[1]

In [12]:
df['Year']= df['Date_Of_Journey'].str.split('-').str[0]

In [13]:
df.head()

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,04,2025
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,03,2025
2,Akasa Air,2025-05-25,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032,25,05,2025
3,Vistara,2025-02-17,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971,17,02,2025
4,Go First,2025-05-25,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859,25,05,2025

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          1000 non-null   object
 1   Date_Of_Journey  1000 non-null   object
 2   Flight           1000 non-null   object
 3   Source_City      1000 non-null   object
 4   Destination      1000 non-null   object
 5   Route            1000 non-null   object
 6   Departure_Time   1000 non-null   object
 7   Arrivala_Time    1000 non-null   object
 8   Total_Stops      1000 non-null   object
 9   Class            1000 non-null   object
 10  Duration         1000 non-null   object
 11  Days_Left        1000 non-null   int64
 12  Price            1000 non-null   int64
 13  Date             1000 non-null   object
 14  Month            1000 non-null   object
 15  Year             1000 non-null   object
dtypes: int64(2), object(14)
memory usage: 125.1+ KB

In [15]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          1000 non-null   object
 1   Date_Of_Journey  1000 non-null   object
 2   Flight           1000 non-null   object
 3   Source_City      1000 non-null   object
 4   Destination      1000 non-null   object
 5   Route            1000 non-null   object
 6   Departure_Time   1000 non-null   object
 7   Arrivala_Time    1000 non-null   object
 8   Total_Stops      1000 non-null   object
 9   Class            1000 non-null   object
 10  Duration         1000 non-null   object
 11  Days_Left        1000 non-null   int64
 12  Price            1000 non-null   int64
 13  Date             1000 non-null   int64
 14  Month            1000 non-null   int64
 15  Year             1000 non-null   int64
dtypes: int64(5), object(11)
memory usage: 125.1+ KB

In [17]:
df.head(2)

,Airline,Date_Of_Journey,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year
0,Akasa Air,2025-04-22,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,4,2025
1,Akasa Air,2025-03-12,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,3,2025

In [18]:
df.drop('Date_Of_Journey', axis=1, inplace= True)

In [19]:
df.head(2)

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,4,2025
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,3,2025

In [ ]:
df['Arrivala_Time'].str.split(':')

0      [2025-04-23 03, 11, 00]
1      [2025-03-12 12, 37, 00]
2      [2025-05-25 09, 52, 00]
3      [2025-02-17 07, 49, 00]
4      [2025-05-25 12, 29, 00]
                ...
995    [2025-03-18 01, 46, 00]
996    [2025-05-07 14, 08, 00]
997    [2025-02-20 18, 09, 00]
998    [2025-05-11 09, 47, 00]
999    [2025-05-17 00, 36, 00]
Name: Arrivala_Time, Length: 1000, dtype: object

In [23]:
df['Arrivala_Time'].str.split(' ')

0      [2025-04-23, 03:11:00]
1      [2025-03-12, 12:37:00]
2      [2025-05-25, 09:52:00]
3      [2025-02-17, 07:49:00]
4      [2025-05-25, 12:29:00]
                ...
995    [2025-03-18, 01:46:00]
996    [2025-05-07, 14:08:00]
997    [2025-02-20, 18:09:00]
998    [2025-05-11, 09:47:00]
999    [2025-05-17, 00:36:00]
Name: Arrivala_Time, Length: 1000, dtype: object

In [25]:
df['Arrivala_Time'].str.split(' ').str[1]

0      03:11:00
1      12:37:00
2      09:52:00
3      07:49:00
4      12:29:00
         ...
995    01:46:00
996    14:08:00
997    18:09:00
998    09:47:00
999    00:36:00
Name: Arrivala_Time, Length: 1000, dtype: object

In [26]:
df['Arrival_hours'] = df['Arrivala_Time'].str.split(' ').str[1].str.split(':').str[0]

In [27]:
df.head()

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year,Arrival_hours
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,4,2025,03
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,3,2025,12
2,Akasa Air,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032,25,5,2025,09
3,Vistara,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971,17,2,2025,07
4,Go First,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859,25,5,2025,12

In [28]:
df['Arrival_minute'] = df['Arrivala_Time'].str.split(' ').str[1].str.split(':').str[1]

In [29]:
df.head()

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year,Arrival_hours,Arrival_minute
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,4,2025,03,11
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,3,2025,12,37
2,Akasa Air,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032,25,5,2025,09,52
3,Vistara,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971,17,2,2025,07,49
4,Go First,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859,25,5,2025,12,29

In [30]:
df['Arrival_second'] = df['Arrivala_Time'].str.split(' ').str[1].str.split(':').str[2]

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Airline         1000 non-null   object
 1   Flight          1000 non-null   object
 2   Source_City     1000 non-null   object
 3   Destination     1000 non-null   object
 4   Route           1000 non-null   object
 5   Departure_Time  1000 non-null   object
 6   Arrivala_Time   1000 non-null   object
 7   Total_Stops     1000 non-null   object
 8   Class           1000 non-null   object
 9   Duration        1000 non-null   object
 10  Days_Left       1000 non-null   int64
 11  Price           1000 non-null   int64
 12  Date            1000 non-null   int64
 13  Month           1000 non-null   int64
 14  Year            1000 non-null   int64
 15  Arrival_hours   1000 non-null   object
 16  Arrival_minute  1000 non-null   object
 17  Arrival_second  1000 non-null   object
dtypes: int64(5), object(13)
memory usage: 140.8+ KB

In [32]:
df.head()

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,4,2025,03,11,00
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,3,2025,12,37,00
2,Akasa Air,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,38,15032,25,5,2025,09,52,00
3,Vistara,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,19,12971,17,2,2025,07,49,00
4,Go First,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,20,5859,25,5,2025,12,29,00

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Airline         1000 non-null   object
 1   Flight          1000 non-null   object
 2   Source_City     1000 non-null   object
 3   Destination     1000 non-null   object
 4   Route           1000 non-null   object
 5   Departure_Time  1000 non-null   object
 6   Arrivala_Time   1000 non-null   object
 7   Total_Stops     1000 non-null   object
 8   Class           1000 non-null   object
 9   Duration        1000 non-null   object
 10  Days_Left       1000 non-null   int64
 11  Price           1000 non-null   int64
 12  Date            1000 non-null   int64
 13  Month           1000 non-null   int64
 14  Year            1000 non-null   int64
 15  Arrival_hours   1000 non-null   object
 16  Arrival_minute  1000 non-null   object
 17  Arrival_second  1000 non-null   object
dtypes: int64(5), object(13)
memory usage: 140.8+ KB

In [35]:
df['Arrival_hours' ]=df['Arrival_hours' ].astype(int)
df['Arrival_minute' ]=df['Arrival_minute' ].astype(int)
df['Arrival_second' ]=df['Arrival_second' ].astype(int)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Airline         1000 non-null   object
 1   Flight          1000 non-null   object
 2   Source_City     1000 non-null   object
 3   Destination     1000 non-null   object
 4   Route           1000 non-null   object
 5   Departure_Time  1000 non-null   object
 6   Arrivala_Time   1000 non-null   object
 7   Total_Stops     1000 non-null   object
 8   Class           1000 non-null   object
 9   Duration        1000 non-null   object
 10  Days_Left       1000 non-null   int64
 11  Price           1000 non-null   int64
 12  Date            1000 non-null   int64
 13  Month           1000 non-null   int64
 14  Year            1000 non-null   int64
 15  Arrival_hours   1000 non-null   int64
 16  Arrival_minute  1000 non-null   int64
 17  Arrival_second  1000 non-null   int64
dtypes: int64(8), object(10)
memory usage: 140.8+ KB

In [37]:
df.head(2)

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,4,2025,3,11,0
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,3,2025,12,37,0

In [41]:
df['Departure_hour']= df['Departure_Time'].str.split(' ').str[1].str.split(':').str[0]

In [42]:
df.head(2)

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second,Departure_hour
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,4,2025,3,11,0,21
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,3,2025,12,37,0,06

In [47]:
df['Departure_minute']= df['Departure_Time'].str.split(' ').str[1].str.split(':').str[1]

In [44]:
df.head(2)

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second,Departure_hour,Departure_minute
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,55,9748,22,4,2025,3,11,0,21,10
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,48,17718,12,3,2025,12,37,0,06,20

In [48]:
df['Departure_second']= df['Departure_Time'].str.split(' ').str[1].str.split(':').str[2]

In [49]:
df.head(2)

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,...,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second,Departure_hour,Departure_minute,Departure_second
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,...,9748,22,4,2025,3,11,0,21,10,00
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,...,17718,12,3,2025,12,37,0,06,20,00

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           1000 non-null   object
 1   Flight            1000 non-null   object
 2   Source_City       1000 non-null   object
 3   Destination       1000 non-null   object
 4   Route             1000 non-null   object
 5   Departure_Time    1000 non-null   object
 6   Arrivala_Time     1000 non-null   object
 7   Total_Stops       1000 non-null   object
 8   Class             1000 non-null   object
 9   Duration          1000 non-null   object
 10  Days_Left         1000 non-null   int64
 11  Price             1000 non-null   int64
 12  Date              1000 non-null   int64
 13  Month             1000 non-null   int64
 14  Year              1000 non-null   int64
 15  Arrival_hours     1000 non-null   int64
 16  Arrival_minute    1000 non-null   int64
 17  Arrival_second    1000 non-null   int64
 18  Departure_hour    1000 non-null   object
 19  Departure_minute  1000 non-null   object
 20  Departure_second  1000 non-null   object
dtypes: int64(8), object(13)
memory usage: 164.2+ KB

In [51]:
df['Departure_hour'] = df['Departure_hour'].astype(int)
df['Departure_minute'] = df['Departure_minute'].astype(int)
df['Departure_second'] = df['Departure_second'].astype(int)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           1000 non-null   object
 1   Flight            1000 non-null   object
 2   Source_City       1000 non-null   object
 3   Destination       1000 non-null   object
 4   Route             1000 non-null   object
 5   Departure_Time    1000 non-null   object
 6   Arrivala_Time     1000 non-null   object
 7   Total_Stops       1000 non-null   object
 8   Class             1000 non-null   object
 9   Duration          1000 non-null   object
 10  Days_Left         1000 non-null   int64
 11  Price             1000 non-null   int64
 12  Date              1000 non-null   int64
 13  Month             1000 non-null   int64
 14  Year              1000 non-null   int64
 15  Arrival_hours     1000 non-null   int64
 16  Arrival_minute    1000 non-null   int64
 17  Arrival_second    1000 non-null   int64
 18  Departure_hour    1000 non-null   int64
 19  Departure_minute  1000 non-null   int64
 20  Departure_second  1000 non-null   int64
dtypes: int64(11), object(10)
memory usage: 164.2+ KB

In [53]:
df.head()

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Arrivala_Time,Total_Stops,Class,Duration,...,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second,Departure_hour,Departure_minute,Departure_second
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,2025-04-23 03:11:00,1 Stop,Economy,6h 1m,...,9748,22,4,2025,3,11,0,21,10,0
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2025-03-12 12:37:00,2+ Stops,Business,6h 17m,...,17718,12,3,2025,12,37,0,6,20,0
2,Akasa Air,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,2025-05-25 09:52:00,Non-stop,Business,1h 37m,...,15032,25,5,2025,9,52,0,8,15,0
3,Vistara,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2025-02-17 07:49:00,2+ Stops,Economy,7h 29m,...,12971,17,2,2025,7,49,0,0,20,0
4,Go First,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,2025-05-25 12:29:00,1 Stop,Economy,3h 29m,...,5859,25,5,2025,12,29,0,9,0,0

In [54]:
df.drop('Arrivala_Time', axis=1, inplace=True)

In [55]:
df.head()

,Airline,Flight,Source_City,Destination,Route,Departure_Time,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second,Departure_hour,Departure_minute,Departure_second
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,2025-04-22 21:10:00,1 Stop,Economy,6h 1m,55,9748,22,4,2025,3,11,0,21,10,0
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2025-03-12 06:20:00,2+ Stops,Business,6h 17m,48,17718,12,3,2025,12,37,0,6,20,0
2,Akasa Air,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,2025-05-25 08:15:00,Non-stop,Business,1h 37m,38,15032,25,5,2025,9,52,0,8,15,0
3,Vistara,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2025-02-17 00:20:00,2+ Stops,Economy,7h 29m,19,12971,17,2,2025,7,49,0,0,20,0
4,Go First,G89244,Chennai,Mumbai,Chennai -> Mumbai,2025-05-25 09:00:00,1 Stop,Economy,3h 29m,20,5859,25,5,2025,12,29,0,9,0,0

In [56]:
df.drop('Departure_Time', axis=1, inplace=True)

In [57]:
df.head()

,Airline,Flight,Source_City,Destination,Route,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second,Departure_hour,Departure_minute,Departure_second
0,Akasa Air,QP439,Mumbai,Hyderabad,Mumbai -> Hyderabad,1 Stop,Economy,6h 1m,55,9748,22,4,2025,3,11,0,21,10,0
1,Akasa Air,QP7156,Bangalore,Mumbai,Bangalore -> Mumbai,2+ Stops,Business,6h 17m,48,17718,12,3,2025,12,37,0,6,20,0
2,Akasa Air,QP5815,Bangalore,Hyderabad,Bangalore -> Hyderabad,Non-stop,Business,1h 37m,38,15032,25,5,2025,9,52,0,8,15,0
3,Vistara,UK7555,Hyderabad,Bangalore,Hyderabad -> Bangalore,2+ Stops,Economy,7h 29m,19,12971,17,2,2025,7,49,0,0,20,0
4,Go First,G89244,Chennai,Mumbai,Chennai -> Mumbai,1 Stop,Economy,3h 29m,20,5859,25,5,2025,12,29,0,9,0,0

In [58]:
df.drop('Route', axis=1, inplace=True)

In [59]:
df.head()

,Airline,Flight,Source_City,Destination,Total_Stops,Class,Duration,Days_Left,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second,Departure_hour,Departure_minute,Departure_second
0,Akasa Air,QP439,Mumbai,Hyderabad,1 Stop,Economy,6h 1m,55,9748,22,4,2025,3,11,0,21,10,0
1,Akasa Air,QP7156,Bangalore,Mumbai,2+ Stops,Business,6h 17m,48,17718,12,3,2025,12,37,0,6,20,0
2,Akasa Air,QP5815,Bangalore,Hyderabad,Non-stop,Business,1h 37m,38,15032,25,5,2025,9,52,0,8,15,0
3,Vistara,UK7555,Hyderabad,Bangalore,2+ Stops,Economy,7h 29m,19,12971,17,2,2025,7,49,0,0,20,0
4,Go First,G89244,Chennai,Mumbai,1 Stop,Economy,3h 29m,20,5859,25,5,2025,12,29,0,9,0,0

In [62]:
df.drop('Days_Left', axis=1, inplace=True)
df.head()

,Airline,Flight,Source_City,Destination,Total_Stops,Class,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second,Departure_hour,Departure_minute,Departure_second
0,Akasa Air,QP439,Mumbai,Hyderabad,1 Stop,Economy,9748,22,4,2025,3,11,0,21,10,0
1,Akasa Air,QP7156,Bangalore,Mumbai,2+ Stops,Business,17718,12,3,2025,12,37,0,6,20,0
2,Akasa Air,QP5815,Bangalore,Hyderabad,Non-stop,Business,15032,25,5,2025,9,52,0,8,15,0
3,Vistara,UK7555,Hyderabad,Bangalore,2+ Stops,Economy,12971,17,2,2025,7,49,0,0,20,0
4,Go First,G89244,Chennai,Mumbai,1 Stop,Economy,5859,25,5,2025,12,29,0,9,0,0

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           1000 non-null   object
 1   Flight            1000 non-null   object
 2   Source_City       1000 non-null   object
 3   Destination       1000 non-null   object
 4   Total_Stops       1000 non-null   object
 5   Class             1000 non-null   object
 6   Price             1000 non-null   int64
 7   Date              1000 non-null   int64
 8   Month             1000 non-null   int64
 9   Year              1000 non-null   int64
 10  Arrival_hours     1000 non-null   int64
 11  Arrival_minute    1000 non-null   int64
 12  Arrival_second    1000 non-null   int64
 13  Departure_hour    1000 non-null   int64
 14  Departure_minute  1000 non-null   int64
 15  Departure_second  1000 non-null   int64
dtypes: int64(10), object(6)
memory usage: 125.1+ KB

In [65]:
df['Total_Stops'].unique()

array(['1 Stop', '2+ Stops', 'Non-stop'], dtype=object)

In [66]:
df['Total_Stops'].mode()

0    2+ Stops
Name: Total_Stops, dtype: object

In [69]:
df['Total_Stops']=df['Total_Stops'].map({'Non-stop':0, '1 Stop' :1, '2+ Stops':2})

In [70]:
df.head()

,Airline,Flight,Source_City,Destination,Total_Stops,Class,Price,Date,Month,Year,Arrival_hours,Arrival_minute,Arrival_second,Departure_hour,Departure_minute,Departure_second
0,Akasa Air,QP439,Mumbai,Hyderabad,1,Economy,9748,22,4,2025,3,11,0,21,10,0
1,Akasa Air,QP7156,Bangalore,Mumbai,2,Business,17718,12,3,2025,12,37,0,6,20,0
2,Akasa Air,QP5815,Bangalore,Hyderabad,0,Business,15032,25,5,2025,9,52,0,8,15,0
3,Vistara,UK7555,Hyderabad,Bangalore,2,Economy,12971,17,2,2025,7,49,0,0,20,0
4,Go First,G89244,Chennai,Mumbai,1,Economy,5859,25,5,2025,12,29,0,9,0,0

In [71]:
df['Airline'].unique()

array(['Akasa Air', 'Vistara', 'Go First', 'SpiceJet', 'Air India',
       'IndiGo'], dtype=object)

In [72]:
df['Source_City'].unique()

array(['Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Delhi', 'Kolkata'],
      dtype=object)

In [73]:
df['Destination'].unique()

array(['Hyderabad', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata', 'Delhi'],
      dtype=object)

In [74]:
from sklearn.preprocessing import OneHotEncoder

In [75]:
encoder = OneHotEncoder()

In [77]:
encoder.fit_transform(df[['Airline','Source_City','Destination']]).toarray()

array([[0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1000, 18))

In [79]:
pd.DataFrame(encoder.fit_transform(df[['Airline','Source_City','Destination']]).toarray(), columns=encoder.get_feature_names_out())

,Airline_Air India,Airline_Akasa Air,Airline_Go First,Airline_IndiGo,Airline_SpiceJet,Airline_Vistara,Source_City_Bangalore,Source_City_Chennai,Source_City_Delhi,Source_City_Hyderabad,Source_City_Kolkata,Source_City_Mumbai,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
996,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
997,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
998,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
999,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0