# Linear Regression

In [37]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
dataset  = pd.read_csv('Algerian_forest_fires_2.csv')

In [39]:
dataset

,Region,Date,Day,Month,Year,Temp,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,Bejaia,04/06/2012,4,June,2012,31,37,13,0.7,41.7,51.6,192.3,12.9,66.7,27.4,Fire
1,Bejaia,29/06/2012,29,June,2012,28,58,12,3.1,87.1,52.1,215.2,11.5,18.8,14.4,Fire
2,Sidi-Bel Abbes,18/06/2012,18,June,2012,41,36,21,6.3,33.4,18.9,164.6,18.4,53.7,1.3,Fire
3,Sidi-Bel Abbes,21/09/2012,21,September,2012,40,56,7,9.5,79.1,34.6,122.1,17.7,61.3,18.7,Not Fire
4,Sidi-Bel Abbes,08/08/2012,8,August,2012,27,32,28,3.1,49.0,51.6,145.2,8.4,19.3,18.6,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,Bejaia,10/06/2012,10,June,2012,37,42,9,8.5,29.8,63.5,217.5,2.2,67.8,4.4,Not Fire
240,Bejaia,12/06/2012,12,June,2012,42,53,20,2.8,38.1,65.3,55.8,0.4,14.9,1.6,Not Fire
241,Bejaia,29/07/2012,29,July,2012,29,40,27,16.3,85.8,55.0,50.9,1.6,24.9,22.1,Not Fire
242,Sidi-Bel Abbes,27/08/2012,27,August,2012,38,52,6,9.6,59.9,9.2,105.9,13.6,6.5,9.3,Not Fire
243,Bejaia,29/08/2012,29,August,2012,29,45,17,12.9,91.5,51.6,74.5,18.4,23.0,22.1,Fire

In [40]:
dataset.head()

,Region,Date,Day,Month,Year,Temp,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,Bejaia,04/06/2012,4,June,2012,31,37,13,0.7,41.7,51.6,192.3,12.9,66.7,27.4,Fire
1,Bejaia,29/06/2012,29,June,2012,28,58,12,3.1,87.1,52.1,215.2,11.5,18.8,14.4,Fire
2,Sidi-Bel Abbes,18/06/2012,18,June,2012,41,36,21,6.3,33.4,18.9,164.6,18.4,53.7,1.3,Fire
3,Sidi-Bel Abbes,21/09/2012,21,September,2012,40,56,7,9.5,79.1,34.6,122.1,17.7,61.3,18.7,Not Fire
4,Sidi-Bel Abbes,08/08/2012,8,August,2012,27,32,28,3.1,49.0,51.6,145.2,8.4,19.3,18.6,Fire

In [41]:
dataset.shape

(244, 16)

In [42]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Region   244 non-null    object
 1   Date     244 non-null    object
 2   Day      244 non-null    int64
 3   Month    244 non-null    object
 4   Year     244 non-null    int64
 5   Temp     244 non-null    int64
 6   RH       244 non-null    int64
 7   Ws       244 non-null    int64
 8   Rain     244 non-null    float64
 9   FFMC     244 non-null    float64
 10  DMC      244 non-null    float64
 11  DC       244 non-null    float64
 12  ISI      244 non-null    float64
 13  BUI      244 non-null    float64
 14  FWI      244 non-null    float64
 15  Classes  244 non-null    object
dtypes: float64(7), int64(5), object(4)
memory usage: 30.6+ KB

## Data Cleaning

In [43]:
dataset.isnull().sum()

Region     0
Date       0
Day        0
Month      0
Year       0
Temp       0
RH         0
Ws         0
Rain       0
FFMC       0
DMC        0
DC         0
ISI        0
BUI        0
FWI        0
Classes    0
dtype: int64

In [44]:
dataset[dataset.isnull().any(axis=1)]   # Data missing check

Empty DataFrame
Columns: [Region, Date, Day, Month, Year, Temp, RH, Ws, Rain, FFMC, DMC, DC, ISI, BUI, FWI, Classes]
Index: []

In [45]:
dataset['Region'] = dataset['Region'].replace({
    'Bejaia': 0,
    'Sidi-Bel Abbes': 1
})

print(dataset.head())

   Region        Date  Day      Month  Year  Temp  RH  Ws  Rain  FFMC   DMC  \
0       0  04/06/2012    4       June  2012    31  37  13   0.7  41.7  51.6
1       0  29/06/2012   29       June  2012    28  58  12   3.1  87.1  52.1
2       1  18/06/2012   18       June  2012    41  36  21   6.3  33.4  18.9
3       1  21/09/2012   21  September  2012    40  56   7   9.5  79.1  34.6
4       1  08/08/2012    8     August  2012    27  32  28   3.1  49.0  51.6

      DC   ISI   BUI   FWI   Classes
0  192.3  12.9  66.7  27.4      Fire
1  215.2  11.5  18.8  14.4      Fire
2  164.6  18.4  53.7   1.3      Fire
3  122.1  17.7  61.3  18.7  Not Fire
4  145.2   8.4  19.3  18.6      Fire

C:\Users\abhay\AppData\Local\Temp\ipykernel_30264\2700355250.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset['Region'] = dataset['Region'].replace({

In [47]:
dataset.head()

,Region,Date,Day,Month,Year,Temp,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,0,04/06/2012,4,June,2012,31,37,13,0.7,41.7,51.6,192.3,12.9,66.7,27.4,Fire
1,0,29/06/2012,29,June,2012,28,58,12,3.1,87.1,52.1,215.2,11.5,18.8,14.4,Fire
2,1,18/06/2012,18,June,2012,41,36,21,6.3,33.4,18.9,164.6,18.4,53.7,1.3,Fire
3,1,21/09/2012,21,September,2012,40,56,7,9.5,79.1,34.6,122.1,17.7,61.3,18.7,Not Fire
4,1,08/08/2012,8,August,2012,27,32,28,3.1,49.0,51.6,145.2,8.4,19.3,18.6,Fire

In [48]:
dataset

,Region,Date,Day,Month,Year,Temp,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,0,04/06/2012,4,June,2012,31,37,13,0.7,41.7,51.6,192.3,12.9,66.7,27.4,Fire
1,0,29/06/2012,29,June,2012,28,58,12,3.1,87.1,52.1,215.2,11.5,18.8,14.4,Fire
2,1,18/06/2012,18,June,2012,41,36,21,6.3,33.4,18.9,164.6,18.4,53.7,1.3,Fire
3,1,21/09/2012,21,September,2012,40,56,7,9.5,79.1,34.6,122.1,17.7,61.3,18.7,Not Fire
4,1,08/08/2012,8,August,2012,27,32,28,3.1,49.0,51.6,145.2,8.4,19.3,18.6,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,0,10/06/2012,10,June,2012,37,42,9,8.5,29.8,63.5,217.5,2.2,67.8,4.4,Not Fire
240,0,12/06/2012,12,June,2012,42,53,20,2.8,38.1,65.3,55.8,0.4,14.9,1.6,Not Fire
241,0,29/07/2012,29,July,2012,29,40,27,16.3,85.8,55.0,50.9,1.6,24.9,22.1,Not Fire
242,1,27/08/2012,27,August,2012,38,52,6,9.6,59.9,9.2,105.9,13.6,6.5,9.3,Not Fire
243,0,29/08/2012,29,August,2012,29,45,17,12.9,91.5,51.6,74.5,18.4,23.0,22.1,Fire

In [49]:
df = dataset

In [50]:
df

,Region,Date,Day,Month,Year,Temp,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,0,04/06/2012,4,June,2012,31,37,13,0.7,41.7,51.6,192.3,12.9,66.7,27.4,Fire
1,0,29/06/2012,29,June,2012,28,58,12,3.1,87.1,52.1,215.2,11.5,18.8,14.4,Fire
2,1,18/06/2012,18,June,2012,41,36,21,6.3,33.4,18.9,164.6,18.4,53.7,1.3,Fire
3,1,21/09/2012,21,September,2012,40,56,7,9.5,79.1,34.6,122.1,17.7,61.3,18.7,Not Fire
4,1,08/08/2012,8,August,2012,27,32,28,3.1,49.0,51.6,145.2,8.4,19.3,18.6,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,0,10/06/2012,10,June,2012,37,42,9,8.5,29.8,63.5,217.5,2.2,67.8,4.4,Not Fire
240,0,12/06/2012,12,June,2012,42,53,20,2.8,38.1,65.3,55.8,0.4,14.9,1.6,Not Fire
241,0,29/07/2012,29,July,2012,29,40,27,16.3,85.8,55.0,50.9,1.6,24.9,22.1,Not Fire
242,1,27/08/2012,27,August,2012,38,52,6,9.6,59.9,9.2,105.9,13.6,6.5,9.3,Not Fire
243,0,29/08/2012,29,August,2012,29,45,17,12.9,91.5,51.6,74.5,18.4,23.0,22.1,Fire

In [51]:
df.head()

,Region,Date,Day,Month,Year,Temp,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,0,04/06/2012,4,June,2012,31,37,13,0.7,41.7,51.6,192.3,12.9,66.7,27.4,Fire
1,0,29/06/2012,29,June,2012,28,58,12,3.1,87.1,52.1,215.2,11.5,18.8,14.4,Fire
2,1,18/06/2012,18,June,2012,41,36,21,6.3,33.4,18.9,164.6,18.4,53.7,1.3,Fire
3,1,21/09/2012,21,September,2012,40,56,7,9.5,79.1,34.6,122.1,17.7,61.3,18.7,Not Fire
4,1,08/08/2012,8,August,2012,27,32,28,3.1,49.0,51.6,145.2,8.4,19.3,18.6,Fire

In [52]:
df.tail()

,Region,Date,Day,Month,Year,Temp,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
239,0,10/06/2012,10,June,2012,37,42,9,8.5,29.8,63.5,217.5,2.2,67.8,4.4,Not Fire
240,0,12/06/2012,12,June,2012,42,53,20,2.8,38.1,65.3,55.8,0.4,14.9,1.6,Not Fire
241,0,29/07/2012,29,July,2012,29,40,27,16.3,85.8,55.0,50.9,1.6,24.9,22.1,Not Fire
242,1,27/08/2012,27,August,2012,38,52,6,9.6,59.9,9.2,105.9,13.6,6.5,9.3,Not Fire
243,0,29/08/2012,29,August,2012,29,45,17,12.9,91.5,51.6,74.5,18.4,23.0,22.1,Fire

In [53]:
df.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Region   244 non-null    int64
 1   Date     244 non-null    object
 2   Day      244 non-null    int64
 3   Month    244 non-null    object
 4   Year     244 non-null    int64
 5   Temp     244 non-null    int64
 6   RH       244 non-null    int64
 7   Ws       244 non-null    int64
 8   Rain     244 non-null    float64
 9   FFMC     244 non-null    float64
 10  DMC      244 non-null    float64
 11  DC       244 non-null    float64
 12  ISI      244 non-null    float64
 13  BUI      244 non-null    float64
 14  FWI      244 non-null    float64
 15  Classes  244 non-null    object
dtypes: float64(7), int64(6), object(3)
memory usage: 30.6+ KB