Data Encoder - One hot encoder

In [2]:
import pandas as pd

In [11]:
df = pd.DataFrame({'color':['red','blue','green','green', 'red','blue']})
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [4]:
from sklearn.preprocessing import OneHotEncoder

In [6]:
encoder = OneHotEncoder()

In [7]:
encoder.fit_transform(df[['color']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [12]:
encoder.fit_transform(df[['color']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [19]:
encoded = encoder.fit_transform(df[['color']])

In [20]:
import pandas as pd

In [27]:
encoded_df =pd.DataFrame(encoded.toarray(), columns= encoder.get_feature_names_out())
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [30]:
pd.concat([df,encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0