Data Encoding - Ordinal Encoding

In [1]:
import pandas as pd

In [25]:
df = pd.DataFrame({'size':['small','medium','large','medium', 'small','large']})
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [26]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [32]:
encoded = encoder.fit_transform(df[['size']])

In [33]:
encoded_df = pd.DataFrame(encoded)
encoded_df

     0
0  0.0
1  1.0
2  2.0
3  1.0
4  0.0
5  2.0

In [34]:
pd.concat([encoded_df, df], axis=1)

     0    size
0  0.0   small
1  1.0  medium
2  2.0   large
3  1.0  medium
4  0.0   small
5  2.0   large