### Non Linear Regression Algorithms (Polynomial Regression)

#### Linear Regression Algorithms

In [1]:
import pandas as pd

df = pd.DataFrame({
    'inp' :[1,2,3,4,5],
    'out':[1,4,9,16,25]
})

x = df[['inp']]
y = df['out']

# Modelling (Model Selection)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x, y)
print('Coefficien of Linear Regression Model:', model.coef_)
print('Intercept of Linear Regression Model', model.intercept_)

#  Prediction

y_pred = model.predict(x)

# Evaluation 
from sklearn.metrics import mean_squared_error
from math import sqrt
mse  = mean_squared_error(y, y_pred)
rmse = sqrt(mse)

print('Mean Square Error in Linear Regression :',mse)
print('Root Mean Square Error in Linear Regression :',rmse)
df

Coefficien of Linear Regression Model: [6.]
Intercept of Linear Regression Model -7.000000000000007
Mean Square Error in Linear Regression : 2.800000000000003
Root Mean Square Error in Linear Regression : 1.673320053068152

   inp  out
0    1    1
1    2    4
2    3    9
3    4   16
4    5   25

#### Non-Linear Regression Algorithms

In [2]:
import pandas as pd

df = pd.DataFrame({
    'inp' :[1,2,3,4,5],
    'out':[1,4,9,16,25]
})
df['inp2'] = df['inp']**2

x = df[['inp2','inp']]
y = df['out']
df
# modelling

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)
print('Coefficient of Non Linear Regression :', model.coef_)
print('Intercept of Non Linear Regression :', model.intercept_)

# Prediction
y_pred = model.predict(x)

# Evaluation
from sklearn.metrics import mean_squared_error
from math import sqrt

mse = mean_squared_error(y, y_pred)
rmse = sqrt(mse)

print('Mean Squared Error in Non Linear Regression :', mse)
print('Root Mean Squared Erro in Non Linear Regression :', rmse)

Coefficient of Non Linear Regression : [1.00000000e+00 5.51119353e-16]
Intercept of Non Linear Regression : -1.7763568394002505e-15
Mean Squared Error in Non Linear Regression : 5.127595883936577e-31
Root Mean Squared Erro in Non Linear Regression : 7.160723346098896e-16

In [3]:
df

   inp  out  inp2
0    1    1     1
1    2    4     4
2    3    9     9
3    4   16    16
4    5   25    25