# Random Forest Classifier With Pipeline And Hyperparameter Tuning

In [1]:
import seaborn as sns
df = sns.load_dataset('tips')

In [2]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [5]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [6]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [7]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [8]:
# label incoding 
from sklearn.preprocessing import LabelEncoder

In [10]:
encoder = LabelEncoder()

In [11]:
df['time']= encoder.fit_transform(df['time'])

In [12]:
df.head()

   total_bill   tip     sex smoker  day  time  size
0       16.99  1.01  Female     No  Sun     0     2
1       10.34  1.66    Male     No  Sun     0     3
2       21.01  3.50    Male     No  Sun     0     3
3       23.68  3.31    Male     No  Sun     0     2
4       24.59  3.61  Female     No  Sun     0     4

In [13]:
df['time'].unique()

array([0, 1])

In [15]:
#  Split into Independent and Depependent features
X = df.drop(columns=['time'])

In [16]:
X

     total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [17]:
y = df['time']

In [18]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [19]:
y.unique()

array([0, 1])

In [21]:
#  Train test Split
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size =0.2 , random_state=16)

In [23]:
x_train

     total_bill   tip     sex smoker   day  size
208       24.27  2.03    Male    Yes   Sat     2
173       31.85  3.18    Male    Yes   Sun     2
118       12.43  1.80  Female     No  Thur     2
48        28.55  2.05    Male     No   Sun     3
111        7.25  1.00  Female     No   Sat     1
..          ...   ...     ...    ...   ...   ...
65        20.08  3.15    Male     No   Sat     3
69        15.01  2.09    Male    Yes   Sat     2
121       13.42  1.68  Female     No  Thur     2
238       35.83  4.67  Female     No   Sat     3
169       10.63  2.00  Female    Yes   Sat     2

[195 rows x 6 columns]

In [24]:
x_train.shape

(195, 6)

In [25]:
y_train

208    0
173    0
118    1
48     0
111    0
      ..
65     0
69     0
121    1
238    0
169    0
Name: time, Length: 195, dtype: int64

In [26]:
y_train.shape

(195,)

In [27]:
x_test

     total_bill   tip     sex smoker   day  size
72        26.86  3.14  Female    Yes   Sat     2
149        7.51  2.00    Male     No  Thur     2
29        19.65  3.00  Female     No   Sat     2
191       19.81  4.19  Female    Yes  Thur     2
10        10.27  1.71    Male     No   Sun     2
25        17.81  2.34    Male     No   Sat     4
79        17.29  2.71    Male     No  Thur     2
135        8.51  1.25  Female     No  Thur     2
99        12.46  1.50    Male     No   Fri     2
0         16.99  1.01  Female     No   Sun     2
212       48.33  9.00    Male     No   Sat     4
157       25.00  3.75  Female     No   Sun     4
104       20.92  4.08  Female     No   Sat     2
96        27.28  4.00    Male    Yes   Fri     2
39        31.27  5.00    Male     No   Sat     3
52        34.81  5.20  Female     No   Sun     4
126        8.52  1.48    Male     No  Thur     2
32        15.06  3.00  Female     No   Sat     2
177       14.48  2.00    Male    Yes   Sun     2
188       18.15  3.50  Female    Yes   Sun     3
56        38.01  3.00    Male    Yes   Sat     4
90        28.97  3.00    Male    Yes   Fri     2
51        10.29  2.60  Female     No   Sun     2
142       41.19  5.00    Male     No  Thur     5
7         26.88  3.12    Male     No   Sun     4
235       10.07  1.25    Male     No   Sat     2
240       27.18  2.00  Female    Yes   Sat     2
161       12.66  2.50    Male     No   Sun     2
103       22.42  3.48  Female    Yes   Sat     2
197       43.11  5.00  Female    Yes  Thur     4
83        32.68  5.00    Male    Yes  Thur     2
71        17.07  3.00  Female     No   Sat     3
19        20.65  3.35    Male     No   Sat     3
61        13.81  2.00    Male    Yes   Sat     2
3         23.68  3.31    Male     No   Sun     2
9         14.78  3.23    Male     No   Sun     2
232       11.61  3.39    Male     No   Sat     2
202       13.00  2.00  Female    Yes  Thur     2
183       23.17  6.50    Male    Yes   Sun     4
152       17.26  2.74    Male     No   Sun     3
134       18.26  3.25  Female     No  Thur     2
78        22.76  3.00    Male     No  Thur     2
68        20.23  2.01    Male     No   Sat     2
189       23.10  4.00    Male    Yes   Sun     3
33        20.69  2.45  Female     No   Sat     4
209       12.76  2.23  Female    Yes   Sat     2
166       20.76  2.24    Male     No   Sun     2
198       13.00  2.00  Female    Yes  Thur     2
139       13.16  2.75  Female     No  Thur     2

In [28]:
x_test.shape

(49, 6)

In [29]:
y_train

208    0
173    0
118    1
48     0
111    0
      ..
65     0
69     0
121    1
238    0
169    0
Name: time, Length: 195, dtype: int64

In [30]:
y_test

72     0
149    1
29     0
191    1
10     0
25     0
79     1
135    1
99     0
0      0
212    0
157    0
104    0
96     0
39     0
52     0
126    1
32     0
177    0
188    0
56     0
90     0
51     0
142    1
7      0
235    0
240    0
161    0
103    0
197    1
83     1
71     0
19     0
61     0
3      0
9      0
232    0
202    1
183    0
152    0
134    1
78     1
68     0
189    0
33     0
209    0
166    0
198    1
139    1
Name: time, dtype: int64

In [31]:
y_test.shape

(49,)

### Feature Engineering Automation using Pipeline

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer  #handling missing values
from sklearn.preprocessing import StandardScaler  # feature scaling
from sklearn.preprocessing import OneHotEncoder # categorical to numerical
from sklearn.compose import ColumnTransformer

In [34]:
categorical_columns = ['sex','smoker','day']
numerical_columns = ['total_bill','tip','size']

In [39]:
num_pipeline= Pipeline(steps=[('imputer',SimpleImputer(strategy='median')),('scaler',StandardScaler())])

In [41]:
cat_pipeline  = Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')), ('OneHotEncoder',OneHotEncoder())])

In [42]:
num_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [43]:
cat_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('OneHotEncoder', OneHotEncoder())])

In [45]:
preprocessor = ColumnTransformer([('num_pipeline',num_pipeline,numerical_columns),
                                  ('cat_pipeline',cat_pipeline,categorical_columns)
                                  ])

In [48]:
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['total_bill', 'tip', 'size']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('OneHotEncoder',
                                                  OneHotEncoder())]),
                                 ['sex', 'smoker', 'day'])])

In [49]:
# Traing and testing data using pipeline above process
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

In [51]:
x_train

array([[ 0.53719385, -0.68496346, -0.59180616, ...,  1.        ,
         0.        ,  0.        ],
       [ 1.40113918,  0.1568355 , -0.59180616, ...,  0.        ,
         1.        ,  0.        ],
       [-0.81229331, -0.85332325, -0.59180616, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-0.69945612, -0.94116315, -0.59180616, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.85476747,  1.24751415,  0.43857064, ...,  1.        ,
         0.        ,  0.        ],
       [-1.01745183, -0.70692343, -0.59180616, ...,  1.        ,
         0.        ,  0.        ]], shape=(195, 11))

In [52]:
x_test

array([[ 0.83239417,  0.12755553, -0.59180616,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-1.37305994, -0.70692343, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.01062031,  0.02507566, -0.59180616,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.02885663,  0.89615459, -0.59180616,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.05848354, -0.91920317, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-0.19909729, -0.45804374,  1.46894744,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.2583653 , -0.18720408, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.25908298, -1.25592276, -0.59180616,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-0.808874  , -1.07292298, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [-0.29255839, -1.43160254, -0.59180616,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 3.27947942,  4.41707024,  1.46894744,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.62039703,  0.57407498,  1.46894744,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 0.15537105,  0.81563468, -0.59180616,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.88026449,  0.75707476, -0.59180616,  0.        ,  1.        ,
         0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [ 1.33503255,  1.48907385,  0.43857064,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 1.73851097,  1.63547367,  1.46894744,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-1.25794321, -1.08756296, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-0.51253392,  0.02507566, -0.59180616,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.57864055, -0.70692343, -0.59180616,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-0.16034512,  0.39107521,  0.43857064,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 2.10323723,  0.02507566,  1.46894744,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 1.07288555,  0.02507566, -0.59180616,  0.        ,  1.        ,
         0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [-1.056204  , -0.26772398, -0.59180616,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 2.46568395,  1.48907385,  2.49932423,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.83467371,  0.11291555,  1.46894744,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-1.08127893, -1.25592276, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.8688668 , -0.70692343, -0.59180616,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.78607861, -0.34092389, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 0.32633648,  0.37643523, -0.59180616,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 2.68451971,  1.48907385,  1.46894744,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 1.49574006,  1.48907385, -0.59180616,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-0.28344023,  0.02507566,  0.43857064,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.12459727,  0.28127534,  0.43857064,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.65500511, -0.70692343, -0.59180616,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.46994745,  0.25199538, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-0.54444746,  0.19343545, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-0.90575441,  0.31055531, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.74732645, -0.70692343, -0.59180616,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.4118192 ,  2.5870725 ,  1.46894744,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-0.26178461, -0.1652441 ,  0.43857064,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-0.14780765,  0.20807544, -0.59180616,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.36508865,  0.02507566, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.07672695, -0.69960344, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.40384081,  0.75707476,  0.43857064,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 0.12915635, -0.37752384,  1.46894744,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.77468091, -0.53856364, -0.59180616,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.13713474, -0.53124365, -0.59180616,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-0.74732645, -0.70692343, -0.59180616,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-0.72909013, -0.15792411, -0.59180616,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ]])

####  Model Building Using  - Random Forest

In [53]:
from sklearn.ensemble import RandomForestClassifier

In [55]:
rfc = RandomForestClassifier()

In [56]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [57]:
y_pred = rfc.predict(x_test)

In [58]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1])

In [59]:
y_test

72     0
149    1
29     0
191    1
10     0
25     0
79     1
135    1
99     0
0      0
212    0
157    0
104    0
96     0
39     0
52     0
126    1
32     0
177    0
188    0
56     0
90     0
51     0
142    1
7      0
235    0
240    0
161    0
103    0
197    1
83     1
71     0
19     0
61     0
3      0
9      0
232    0
202    1
183    0
152    0
134    1
78     1
68     0
189    0
33     0
209    0
166    0
198    1
139    1
Name: time, dtype: int64

In [60]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

1.0
[[36  0]
 [ 0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        13

    accuracy                           1.00        49
   macro avg       1.00      1.00      1.00        49
weighted avg       1.00      1.00      1.00        49

##### Hyper parameter tuning

In [61]:
classifier = RandomForestClassifier()

In [62]:
parameter = {
    'max_depth':[3,5,10,None],

    'n_estimators':[100, 200, 300],
    'criterion':['gini','entropy']
}

In [63]:
from sklearn.model_selection import RandomizedSearchCV

In [67]:
cv = RandomizedSearchCV(classifier,param_distributions=parameter, cv = 5, scoring='accuracy', verbose=3)

In [68]:
cv.fit(x_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=gini, max_depth=5, n_estimators=300;, score=0.897 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, n_estimators=300;, score=1.000 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, n_estimators=300;, score=0.923 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, n_estimators=300;, score=0.949 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, n_estimators=300;, score=0.923 total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, n_estimators=100;, score=0.897 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, n_estimators=100;, score=1.000 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, n_estimators=100;, score=0.923 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, n_estimators=100;, score=0.949 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, n_estimators=100;, score=0.923 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=3, n_estimators=300;, score=0.897 total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=3, n_estimators=300;, score=1.000 total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=3, n_estimators=300;, score=0.923 total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=3, n_estimators=300;, score=0.949 total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=3, n_estimators=300;, score=0.974 total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=0.897 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=0.923 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=0.949 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=0.974 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, n_estimators=200;, score=0.897 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, n_estimators=200;, score=1.000 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, n_estimators=200;, score=0.923 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, n_estimators=200;, score=0.949 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, n_estimators=200;, score=0.923 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=3, n_estimators=300;, score=0.897 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=3, n_estimators=300;, score=1.000 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=3, n_estimators=300;, score=0.923 total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=3, n_estimators=300;, score=0.949 total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=3, n_estimators=300;, score=0.974 total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=None, n_estimators=300;, score=0.897 total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=None, n_estimators=300;, score=1.000 total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=None, n_estimators=300;, score=0.923 total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=None, n_estimators=300;, score=0.949 total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=None, n_estimators=300;, score=0.923 total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, n_estimators=300;, score=0.897 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=10, n_estimators=300;, score=1.000 total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, n_estimators=300;, score=0.923 total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, n_estimators=300;, score=0.949 total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, n_estimators=300;, score=0.923 total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, n_estimators=200;, score=0.897 total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, n_estimators=200;, score=1.000 total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, n_estimators=200;, score=0.923 total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, n_estimators=200;, score=0.949 total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=10, n_estimators=200;, score=0.923 total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, n_estimators=300;, score=0.897 total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, n_estimators=300;, score=1.000 total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=10, n_estimators=300;, score=0.923 total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, n_estimators=300;, score=0.949 total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, n_estimators=300;, score=0.923 total time=   0.2s

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [3, 5, 10, None],
                                        'n_estimators': [100, 200, 300]},
                   scoring='accuracy', verbose=3)

In [69]:
cv.best_params_

{'n_estimators': 300, 'max_depth': 3, 'criterion': 'entropy'}

#### Model Training Automation

In [70]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [71]:
models = {
    'Random Forest':RandomForestClassifier(),
    'Logistic Regression':LogisticRegression(),
    'Decision Tree':DecisionTreeClassifier()
}

In [72]:
from sklearn.metrics import accuracy_score

In [78]:
def evaluate_model(x_train, y_train, x_test, y_test, models):
    report={}
    for i in range(len(models)):
        model = list(models.values())[i]
        # train model
        model.fit(x_train, y_train)


        # predict  testing data
        y_test_pred = model.predict(x_test)


        #  get accuracy for  test data  prediction
        test_model_score = accuracy_score(y_test_pred, y_test)
        report[list(models.keys())[i]] =test_model_score
    

    return report

In [79]:
evaluate_model(x_train, y_train, x_test, y_test, models)

{'Random Forest': 0.9795918367346939,
 'Logistic Regression': 1.0,
 'Decision Tree': 1.0}